# frozen_string_literal: true

require "json"

module MCP
  module Protocol
    class Handler
      BATCH_REFUSAL = JSON.generate(
        jsonrpc: JsonRpcHandler::Version::V2_0,
        id: nil,
        error: {
          code: JsonRpcHandler::ErrorCode::INVALID_REQUEST,
          message: "Invalid Request",
          data: "This server takes one request per POST, not a batch",
        },
      )
      CONTEXT = {
        accept_suggestion_edits: "suggestions.operations.accept_suggestion_edits",
        add_decision_comment: "api.endpoints.add_decision_comment",
        add_decision_option: "api.endpoints.add_decision_option",
        add_task_comment: "api.endpoints.add_task_comment",
        add_work_entry: "projects.operations.add_work_entry",
        all_tags: "tags.queries.all",
        analytics_between: "analytics.queries.summary_between",
        approve_webmentions: "api.endpoints.approve_webmentions",
        archive_project: "projects.operations.archive_project",
        archived_projects: "projects.queries.archived",
        cancel_task: "api.endpoints.cancel_task",
        cancel_tasks: "api.endpoints.cancel_tasks",
        capture_task: "api.endpoints.capture_task",
        clicks_between: "analytics.queries.clicks_between",
        commits_between: "record.queries.commits_between",
        commits_last_synced_at: "record.queries.commits_last_synced_at",
        complete_task: "api.endpoints.complete_task",
        complete_tasks: "api.endpoints.complete_tasks",
        compose_announcement: "posts.operations.compose_announcement",
        compose_social_post: "social.operations.compose_social_post",
        create_journal_entry: "api.endpoints.create_journal_entry",
        create_person: "api.endpoints.create_person",
        create_saved_view: "api.endpoints.create_saved_view",
        create_task_tag_rule: "api.endpoints.create_task_tag_rule",
        dated_posts: "posts.queries.dated_between",
        delete_decision_comment: "api.endpoints.delete_decision_comment",
        delete_decision_option: "api.endpoints.delete_decision_option",
        delete_journal_entry: "api.endpoints.delete_journal_entry",
        delete_messages: "api.endpoints.delete_messages",
        delete_person: "api.endpoints.delete_person",
        delete_post: "posts.operations.delete_post",
        delete_posts: "api.endpoints.delete_posts",
        delete_saved_view: "api.endpoints.delete_saved_view",
        delete_social_post: "social.operations.delete_social_post",
        delete_task: "api.endpoints.delete_task",
        delete_task_comment: "api.endpoints.delete_task_comment",
        delete_task_tag_rule: "api.endpoints.delete_task_tag_rule",
        delete_tasks: "api.endpoints.delete_tasks",
        delete_work_entry: "projects.operations.delete_work_entry",
        delete_work_session: "api.endpoints.delete_work_session",
        devices_between: "analytics.queries.devices_between",
        drop_decision: "api.endpoints.drop_decision",
        drop_sprint: "api.endpoints.drop_sprint",
        edit_decision: "api.endpoints.edit_decision",
        edit_decision_comment: "api.endpoints.edit_decision_comment",
        edit_decision_option: "api.endpoints.edit_decision_option",
        edit_task_comment: "api.endpoints.edit_task_comment",
        editable_social_post: "social.queries.editable_social_post",
        feed_subscribers_between: "analytics.queries.feed_subscribers_between",
        first_days: "analytics.queries.first_days",
        hourly_between: "analytics.queries.hourly_between",
        ignore_webmentions: "api.endpoints.ignore_webmentions",
        link_records: "api.endpoints.link_records",
        link_tasks: "api.endpoints.link_tasks",
        list_attention: "api.endpoints.list_attention",
        list_calendar: "api.endpoints.list_calendar",
        list_decisions: "api.endpoints.list_decisions",
        list_inbox: "api.endpoints.list_inbox",
        list_journal_entries: "api.endpoints.list_journal_entries",
        list_links: "api.endpoints.list_links",
        list_people: "api.endpoints.list_people",
        list_saved_views: "api.endpoints.list_saved_views",
        list_sprints: "api.endpoints.list_sprints",
        list_task_tag_rules: "api.endpoints.list_task_tag_rules",
        list_tasks: "api.endpoints.list_tasks",
        list_webmentions: "api.endpoints.list_webmentions",
        live_projects: "projects.queries.live",
        mark_message: "contact.operations.mark_message",
        mark_messages_read: "api.endpoints.mark_messages_read",
        mark_messages_unread: "api.endpoints.mark_messages_unread",
        mark_task_seen: "api.endpoints.mark_task_seen",
        mark_webmentions_spam: "api.endpoints.mark_webmentions_spam",
        matching_tags: "tags.queries.matching",
        message_by_id: "contact.queries.by_id",
        messages_between: "contact.queries.received_between",
        moderate_webmention: "social.operations.moderate_webmention",
        move_project: "projects.operations.move_project",
        move_task: "api.endpoints.move_task",
        move_tasks: "api.endpoints.move_tasks",
        navigation_between: "analytics.queries.navigation_between",
        open_decision: "api.endpoints.open_decision",
        page_between: "analytics.queries.page_between",
        pause_task: "api.endpoints.pause_task",
        pending_webmention_count: "social.queries.pending_webmention_count",
        plan_sprint: "api.endpoints.plan_sprint",
        post_by_id: "posts.queries.by_id",
        posts_by_ids: "posts.queries.by_ids",
        project_by_id: "projects.queries.by_id",
        publish_post: "api.endpoints.publish_post",
        published_post_by_slug: "posts.queries.published_by_slug",
        queue_commit_import: "record.operations.queue_commit_import",
        reach_between: "analytics.queries.reach_between",
        read_activity: "api.endpoints.read_activity",
        read_commit: "api.endpoints.read_commit",
        read_current_sprint: "api.endpoints.read_current_sprint",
        read_decision: "api.endpoints.read_decision",
        read_journal_entry: "api.endpoints.read_journal_entry",
        read_person: "api.endpoints.read_person",
        read_post: "api.endpoints.read_post",
        read_project: "api.endpoints.read_project",
        read_review: "api.endpoints.read_review",
        read_saved_view: "api.endpoints.read_saved_view",
        read_social_post: "api.endpoints.read_social_post",
        read_spread_between: "analytics.queries.read_spread_between",
        read_task: "api.endpoints.read_task",
        read_throughs_between: "analytics.queries.read_throughs_between",
        read_time_report: "api.endpoints.read_time_report",
        read_webmention: "api.endpoints.read_webmention",
        read_work_entry: "api.endpoints.read_work_entry",
        readers_by_path: "analytics.queries.readers_by_path",
        reject_edits: "suggestions.operations.reject_edits",
        remove_tag: "tags.operations.remove_tag",
        reopen_decision: "api.endpoints.reopen_decision",
        reopen_task: "api.endpoints.reopen_task",
        reorder_task: "api.endpoints.reorder_task",
        replace_post_edits: "suggestions.operations.replace_post_edits",
        replace_social_post_edits: "suggestions.operations.replace_social_post_edits",
        resolve_decision: "api.endpoints.resolve_decision",
        restore_project: "projects.operations.restore_project",
        save_post: "posts.operations.save_post",
        save_post_seo: "posts.operations.save_post_seo",
        save_project: "projects.operations.save_project",
        save_review_note: "api.endpoints.save_review_note",
        save_tag: "tags.operations.save_tag",
        save_task: "api.endpoints.save_task",
        schedule_task: "api.endpoints.schedule_task",
        scroll_depths_between: "analytics.queries.scroll_depths_between",
        search: "api.endpoints.search",
        search_accounts: "api.endpoints.search_accounts",
        set_task_total: "api.endpoints.set_task_total",
        social_posts_dated_between: "social.queries.social_posts_dated_between",
        snooze_attention: "api.endpoints.snooze_attention",
        sources_between: "analytics.queries.sources_between",
        start_task: "api.endpoints.start_task",
        suggestion_by_id: "suggestions.queries.by_id",
        suggestions_between: "suggestions.queries.created_between",
        summarize_activity: "api.endpoints.summarize_activity",
        sync_failures: "record.queries.sync_failures",
        sync_issues: "api.endpoints.sync_issues",
        tag_by_id: "tags.queries.by_id",
        tag_decision: "api.endpoints.tag_decision",
        tag_posts: "api.endpoints.tag_posts",
        tag_tasks: "api.endpoints.tag_tasks",
        tag_usage: "tags.queries.usage",
        unlink_records: "api.endpoints.unlink_records",
        unlink_task: "api.endpoints.unlink_task",
        unsent_social_posts: "social.queries.unsent_social_posts",
        untag_decision: "api.endpoints.untag_decision",
        untag_tasks: "api.endpoints.untag_tasks",
        update_journal_entry: "api.endpoints.update_journal_entry",
        update_person: "api.endpoints.update_person",
        update_post_edit_note: "api.endpoints.update_post_edit_note",
        update_saved_view: "api.endpoints.update_saved_view",
        update_task_tag_rule: "api.endpoints.update_task_tag_rule",
        update_webmention_settings: "social.operations.update_webmention_settings",
        update_work_session: "api.endpoints.update_work_session",
        upload_photo: "api.endpoints.upload_photo",
        webmention_settings: "social.queries.webmention_settings",
        webmentions_received_between: "social.queries.webmentions_received_between",
        webmentions_received_by_post: "social.queries.webmentions_received_by_post",
        weekday_hours: "analytics.queries.weekday_hours",
        work_entries_between: "projects.queries.work_entries_between",
      }.freeze
      INSTRUCTIONS = [
        "Read everything %s's site keeps: posts, social posts, announcements, webmentions and their settings,",
        "the journal, commits and the sync state, tasks, sprints, task tag rules, work sessions and the time report,",
        "projects, work history, decisions, people, tags, record links, saved views, messages, the inbox, attention,",
        "the calendar, the review, suggestions, analytics and the whole activity feed. Search every kind by its",
        "words, and look up accounts on Mastodon and Bluesky. Suggest edits to a post or social post, and settle",
        "suggestions with accept_suggestion_edits and reject_suggestion_edits or leave them for the owner in the",
        "admin. Make any change the admin makes, publishing, sending and deleting included. A published post or a",
        "sent social post cannot be called back. The tool list holds only what this connection was granted.",
        Tools::Untrusted::WARNING,
      ].join(" ").freeze
      PROMPTS = [Prompts::Proofread, Prompts::Report].freeze
      TITLE = "%s's site"
      TOOLS = [
        Tools::AcceptSuggestionEdits,
        Tools::AddDecisionComment,
        Tools::AddDecisionOption,
        Tools::AddTaskComment,
        Tools::AddWorkEntry,
        Tools::ApproveWebmentions,
        Tools::ArchiveProject,
        Tools::CancelTask,
        Tools::CancelTasks,
        Tools::CaptureTask,
        Tools::CompleteTask,
        Tools::CompleteTasks,
        Tools::ComposeAnnouncement,
        Tools::CreateJournalEntry,
        Tools::CreatePost,
        Tools::CreateSavedView,
        Tools::CreateSocialPost,
        Tools::DeleteDecisionComment,
        Tools::DeleteDecisionOption,
        Tools::DeleteJournalEntry,
        Tools::DeleteMessages,
        Tools::DeletePerson,
        Tools::DeletePost,
        Tools::DeletePosts,
        Tools::DeleteSavedView,
        Tools::DeleteSocialPost,
        Tools::DeleteTask,
        Tools::DeleteTaskComment,
        Tools::DeleteTaskTagRule,
        Tools::DeleteTasks,
        Tools::DeleteWorkEntry,
        Tools::DeleteWorkSession,
        Tools::DropDecision,
        Tools::DropSprint,
        Tools::EditDecision,
        Tools::EditDecisionComment,
        Tools::EditDecisionOption,
        Tools::EditTaskComment,
        Tools::IgnoreWebmentions,
        Tools::ImportCommits,
        Tools::LinkRecords,
        Tools::LinkTasks,
        Tools::ListAttention,
        Tools::ListCalendar,
        Tools::ListCommits,
        Tools::ListDecisions,
        Tools::ListInbox,
        Tools::ListJournalEntries,
        Tools::ListLinks,
        Tools::ListMessages,
        Tools::ListPeople,
        Tools::ListPosts,
        Tools::ListProjects,
        Tools::ListSavedViews,
        Tools::ListSocialPosts,
        Tools::ListSprints,
        Tools::ListSuggestions,
        Tools::ListTags,
        Tools::ListTaskTagRules,
        Tools::ListTasks,
        Tools::ListWebmentions,
        Tools::ListWorkEntries,
        Tools::MarkMessage,
        Tools::MarkMessagesRead,
        Tools::MarkMessagesUnread,
        Tools::MarkTaskSeen,
        Tools::MarkWebmentionsSpam,
        Tools::ModerateWebmention,
        Tools::MoveProject,
        Tools::MoveTask,
        Tools::MoveTasks,
        Tools::OpenDecision,
        Tools::PauseTask,
        Tools::PlanSprint,
        Tools::PublishPost,
        Tools::ReadActivity,
        Tools::ReadAnalytics,
        Tools::ReadCommit,
        Tools::ReadCurrentSprint,
        Tools::ReadDecision,
        Tools::ReadJournalEntry,
        Tools::ReadMessage,
        Tools::ReadPerson,
        Tools::ReadPost,
        Tools::ReadProject,
        Tools::ReadReview,
        Tools::ReadSavedView,
        Tools::ReadSocialPost,
        Tools::ReadSyncState,
        Tools::ReadTask,
        Tools::ReadTimeReport,
        Tools::ReadWebmention,
        Tools::ReadWebmentionSettings,
        Tools::ReadWorkEntry,
        Tools::RejectSuggestionEdits,
        Tools::RemoveTag,
        Tools::ReopenDecision,
        Tools::ReopenTask,
        Tools::ReorderTask,
        Tools::ResolveDecision,
        Tools::RestoreProject,
        Tools::SavePerson,
        Tools::SaveProject,
        Tools::SaveReviewNote,
        Tools::SaveTag,
        Tools::SaveTask,
        Tools::SaveTaskTagRule,
        Tools::ScheduleTask,
        Tools::Search,
        Tools::SearchAccounts,
        Tools::SendSocialPost,
        Tools::SetTaskTotal,
        Tools::SnoozeAttention,
        Tools::StartTask,
        Tools::SuggestEdits,
        Tools::SummarizeActivity,
        Tools::SyncIssues,
        Tools::TagDecision,
        Tools::TagPosts,
        Tools::TagTasks,
        Tools::UnlinkRecords,
        Tools::UnlinkTask,
        Tools::UntagDecision,
        Tools::UntagTasks,
        Tools::UpdateJournalEntry,
        Tools::UpdatePost,
        Tools::UpdatePostEditNote,
        Tools::UpdateSavedView,
        Tools::UpdateSocialPost,
        Tools::UpdateWebmentionSettings,
        Tools::UpdateWorkSession,
        Tools::UploadPhoto,
        Tools::WritePostSeo,
      ].freeze

      include Deps["settings", honeybadger: "honeybadger.agent", **CONTEXT]

      def call(payload, scopes:) = batch?(payload) ? BATCH_REFUSAL : server(scopes).handle_json(payload)

      private

      def batch?(payload)
        JSON.parse(payload).is_a?(Array)
      rescue JSON::ParserError
        false
      end

      def context = CONTEXT.keys.to_h { [it, public_send(it)] }.merge(page_size: settings.page_size[:mcp])

      def name = Blog::Types::Normalized::Host.call(settings.site[:url])

      def owner = settings.owner[:name]

      def report(error, _context)
        honeybadger.notify(error) unless error.is_a?(Server::RequestHandlerError)
      end

      def server(scopes)
        ScopedServer.new(
          configuration: Configuration.new(exception_reporter: method(:report)),
          instructions: format(INSTRUCTIONS, owner),
          name:,
          prompts: PROMPTS,
          scopes:,
          server_context: context,
          title: format(TITLE, owner),
          tools: TOOLS,
          version: Blog::Version::CURRENT,
        )
      end
    end
  end
end
