#!/usr/bin/env sh
#MISE description="Lint all files for editorconfig violations"
#MISE alias=["l:ec", "l:editorconfig", "lint:ec"]

set -e

if [ -d .git ]; then
  editorconfig-checker -config .config/editorconfig-checker.json
else
  jj file list | tr '\n' '\0' | xargs -0 editorconfig-checker -config .config/editorconfig-checker.json
fi
