#!/usr/bin/env sh
#MISE description="Lint all files for editorconfig violations"
#MISE alias=["l:ec", "l:editorconfig", "lint:ec"]

set -e

editorconfig-checker -config .config/editorconfig-checker.json
