#!/usr/bin/env sh
#MISE description="Start the development server"

set -e

export HANAMI_ENV=development

scripts/util/ensure_postgres bundle exec hanami server --config .config/config.ru --guardfile .config/Guardfile
