#!/usr/bin/env sh
#MISE description="Stop the development environment"

set -e

pitchfork list --project --status running --status waiting --hide-header |
  awk '{ print $1 }' |
  xargs -r pitchfork stop
