#!/usr/bin/env sh
#MISE description="Run tests for the project"
#MISE alias=["t"]

set -e

scripts/assets/build
scripts/test/prepare
scripts/util/ensure_postgres bundle exec rspec --require spec_helper "$@"
